name: Test Prog2

on:
  push:
    branches:
      - prog2

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Create Pull Request
        if: github.event_name == 'push'
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh pr create \
            --base main \
            --head prog2 \
            --title "Integración de prog2 a main" \
            --body "Pull Request generado automáticamente después de validar los cambios de prog2."