#Esta fue creado con guia de un video de YT
name: Test Prog2

on:
  push:
    branches:
      - prog2

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Test workflow
        run: echo "GitHub Actions funciona correctamente"

      - name: Test workflow
        run: 
          echo "Verificando archivos principales..."
          test -f index.html
          test -f css/styles.css
          
          echo "Archivos principales encontrados correctamente."