name: Test Prog2

on:
  push:
    branches:
      - prog2

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Verify project files
        run: |
          echo "Verificando archivos del proyecto..."

          test -f index.html
          test -f css/styles.css

          echo "Archivos principales encontrados correctamente."name: Test Prog2

on:
  push:
    branches:
      - prog2

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Verify project files
        run: |
          echo "Verificando archivos del proyecto..."

          test -f index.html
          test -f css/styles.css

          echo "Archivos principales encontrados correctamente."